"""empty message

Revision ID: 940fbbf9b035
Revises: 716e75c8254b
Create Date: 2026-10-03 13:16:28.620407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "940fbbf9b035"
down_revision = "716e75c8254b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("room_tools", schema=None) as batch_op:
        batch_op.add_column(sa.Column("active", sa.Boolean(), nullable=False))

    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.drop_column("active")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tools", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "active",
                mysql.TINYINT(display_width=1),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("room_tools", schema=None) as batch_op:
        batch_op.drop_column("active")

    # ### end Alembic commands ###
